import type { CSSProperties } from 'react'

import { theme } from '~/theme'

export const styles = {
  Badge: {
    alignItems: 'center',
    background: 'rgba(8,7,5,0.58)',
    border: `1px solid ${theme.colors.line}`,
    borderRadius: theme.radii.pill,
    bottom: 18,
    color: theme.colors.champagne,
    display: 'flex',
    fontFamily: theme.fonts.body,
    fontSize: 10,
    fontWeight: 700,
    gap: 8,
    letterSpacing: '0.13em',
    padding: '9px 12px',
    position: 'absolute',
    right: 18,
    textTransform: 'uppercase',
  } satisfies CSSProperties,
  Canvas: {
    height: '92%',
    left: '4%',
    pointerEvents: 'none',
    position: 'absolute',
    top: '4%',
    width: '92%',
  } satisfies CSSProperties,
  Frame: {
    alignItems: 'center',
    aspectRatio: '1 / 1',
    background:
      'radial-gradient(circle at 50% 42%, rgba(215,180,96,0.105), rgba(17,16,13,0.78) 45%, rgba(5,5,4,0.96) 100%)',
    border: `1px solid ${theme.colors.line}`,
    borderRadius: 'clamp(24px, 4vw, 46px)',
    boxShadow: theme.shadows.strong,
    contain: 'layout paint style',
    display: 'flex',
    isolation: 'isolate',
    justifyContent: 'center',
    maxHeight: 680,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  } satisfies CSSProperties,
  Number: {
    backfaceVisibility: 'hidden',
    color: theme.colors.champagne,
    fontFamily: theme.fonts.display,
    fontSize: 'clamp(82px, 13vw, 170px)',
    fontWeight: 400,
    left: '50%',
    letterSpacing: '-0.08em',
    lineHeight: 0.8,
    pointerEvents: 'none',
    position: 'absolute',
    top: '50%',
    transform: 'translate3d(-52%, -50%, 0)',
    transformOrigin: 'center',
  } satisfies CSSProperties,
}
